[profile]
description = Superpowers with free models

[models]
brainstorm = opencode/big-pickle
planner = opencode/qwen3.6-plus-free
debugger = opencode/qwen3.6-plus-free
execution-orchestrator = opencode/deepseek-v4-flash-free
software-engineer = opencode/deepseek-v4-flash-free
senior-software-engineer = opencode/qwen3.6-plus-free
code-reviewer = opencode/qwen3.6-plus-free
spec-reviewer = opencode/big-pickle
utility = opencode/deepseek-v4-flash-free
