[profile]
description = Economic superpowers profile

[models]
brainstorm = opencode-go/glm-5
planner = opencode-go/kimi-k2.6
debugger = opencode-go/deepseek-v4-pro
execution-orchestrator = opencode-go/kimi-k2.5
software-engineer = opencode-go/kimi-k2.5
senior-software-engineer = opencode-go/kimi-k2.6
code-reviewer = opencode-go/deepseek-v4-pro
spec-reviewer = opencode-go/glm-5
utility = opencode-go/deepseek-v4-flash
